package: 
  name: action-test
  version: 1

source:
  path: ../

requirements:
  build:
    - cmake >=3.17.0
    - {{ compiler('cxx') }} # [linux]
    - clang                 # [osx]

test:
  commands:
    - action-test