name: 'Anaconda Github Action'

on: [push]

jobs:
  build_macos:
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        include:
          - os: macos-latest
            variant_file: macos_build_variants.yaml
          - os: linux-latest
            variant_file: linux_build_variants.yaml

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - run: echo "CONDA=/root/" >> $GITHUB_ENV
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true
        environment-file: etc/conda_build_environment.yaml
        CONDA: ${{ env.CONDA }}

    - run: |
        cd .conda
        mamba mambabuild . -e macos_build_variants.yaml
      with:
        target_os: ${{ matrix.os }}