name: 'Anaconda Github Action'

on: [push]

jobs:
  test_job:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: macos-latest
    # strategy:
    #   matrix:
    #     os: macos-latest #ubuntu-latest, , windows-latest]

    steps:
    - uses: actions/checkout@v2
    - run: echo "CONDA=/root/" >> $GITHUB_ENV
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true
        environment-file: etc/conda_build_environment.yaml
        CONDA: ${{ env.CONDA }}

    - run: |
        cd .conda
        mamba mambabuild . -e macos_build_variants.yaml