name: 'Anaconda Github Action'

on: [push]

jobs:
  test_job:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #ubuntu-latest, , windows-latest]
        
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        miniconda-version: "latest"

    - run: |
      cd .conda/linux;
      conda build . 
    - run: python -c "import fierro_voxelizer;"